export {
  apiSlice,
  useAcceptDeliveryMutation,
  useAddAddressMutation,
  useCreateOrderMutation,
  useGetAddressesQuery,
  useGetAvailableDeliveriesQuery,
  useGetEarningsQuery,
  useGetOrderByIdQuery,
  useGetOrdersQuery,
  useGetProfileQuery,
  useGetRestaurantByIdQuery,
  useGetRestaurantCategoriesQuery,
  useGetRestaurantProductsQuery,
  useGetRestaurantsQuery,
  useLoginMutation,
  useRegisterMutation,
  useUpdateProfileMutation,
} from '../services/apiSlice';
